channels:
    - conda-forge
name:
    stacc
dependencies:
    - bioimageio.core
    - imageio
    - napari
    - pip
    - pooch
    - pyqt
    - pytorch
    - tensorboard
    - torch_em
    - torchvision
    - xarray <2025.3.0
